### ISSUE TITLE
can't find element by role `code`

### ISSUE THREAD

**Issue by chiptus** [testing-library/dom-testing-library#1100]
- `@testing-library/dom` version: 12.1.2
- Testing Framework and version:
jest 27.4.3
  
- DOM Environment:
jsdom 16.6.0
  

### Relevant code or config:

component
```js
export default ({ name }) => <code>{name}</code>;
```

test
```js
import "@testing-library/jest-dom/extend-expect";
import React from "react";
import { render } from "@testing-library/react";
import Code from "../hello";

test("To render a code element", () => {
  const { getByRole } = render(<Code name="Jill" />);
  expect(getByRole("code")).toBeInTheDocument();
});
```

### What you did:
I searched the code element by role `code`, I expected to find it by https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/structural_roles

### What happened:
The element is not found

### Reproduction:
https://codesandbox.io/s/fail-to-find-role-code-qpzrs?file=/src/__tests__/hello.js

### Problem description:
Per testing-library docs, it seems like it should work, as when I check the role of the element in chrome dev tools, I see 'code' as expected.

### Suggested solution:

not sure, I've seen that aria-query doesn't support this role.

**Comment by MatanBobi** [comment]
Hi @chiptus!
Thanks for taking the time to open this one :)
Since the issue you're experiencing here is related to implicit roles, `aria-query` is indeed the package we're using for that.
Though, it's important to note that the Chrome DevTools isn't our source of truth.
We follow the ARIA standards and the way they define [implicit roles](https://www.w3.org/TR/html-aria/).
As you can see here, the standard doesn't dictate an implicit role for `code` element and that's also the reason why `aria-query` aren't supporting that either.
![image](https://user-images.githubusercontent.com/12711091/151713982-89ec47bc-5567-402e-b2c4-9f4f892d9f08.png)

For this specific use-case, I suggest either setting an explicit role on your own or query the element with a different approach :)

I'm closing this one as this is the wanted behavior in this scenario.
Thanks again!

**Comment by EmeraldWeb** [comment]
Hello, I'm sorry but I think it's better to reopen this issue, because there is [corresponding role](https://www.w3.org/TR/html-aria/) "code", now: 

<img width="860" alt="Снимок экрана 2022-12-26 в 16 07 54" src="https://user-images.githubusercontent.com/20793330/209547552-30bbf2d7-63a9-48a4-b4d0-bb9c082bdb97.png">

I have run into this problem today, so it will be cool if you're add this one. Thank you.

**Comment by EmeraldWeb** [comment]
@MatanBobi 
Hello, I'm sorry but I think it's better to reopen this issue, because there is [corresponding role](https://www.w3.org/TR/wai-aria-1.2/#code) "code", now: 

<img width="860" alt="Снимок экрана 2022-12-26 в 16 07 54" src="https://user-images.githubusercontent.com/20793330/209547552-30bbf2d7-63a9-48a4-b4d0-bb9c082bdb97.png">

I have run into this problem today, so it will be cool if you're add this role. Thank you.

**Comment by MatanBobi** [comment]
Thanks @EmeraldWeb!
I see that the spec was updated.
I've opened an issue for `aria-query` regarding this :)

**Comment by CalebJamesStevens** [comment]
Bumping because this issue still isn't resolved

**Comment by MatanBobi** [comment]
@CalebJamesStevens, there's no need to bump this issue, we're waiting for `aria-query` to release a new version, once they will release it, we will upgrade our dependency.
@eps1lon do you know if there's a roadmap for `aria-query` release?

**Comment by jlp-craigmorten** [comment]
[v10.0.0](https://github.com/testing-library/dom-testing-library/releases/tag/v10.0.0) is now live with this update.

**Comment by MatanBobi** [comment]
Thanks @jlp-craigmorten!

@all-contributors please add @jlp-craigmorten for question
