### ISSUE TITLE
`fireEvent.keyPress` should change the value of input

### ISSUE THREAD

**Issue by dehghani-mehdi** [testing-library/dom-testing-library#1105]
Related issue #1104, which is closed without any good reason.

KeyPress means there is a value/character entered by the user, so why RTL doesn't change the value of the input?

**Comment by MatanBobi** [comment]
Hi @dehghani-mehdi.
First, to be honest, I don't like the attitude you're showing here towards maintainers. Maintaining an open source software takes valuable time and instead of showing appreciation for that, you're backlashing on us. We're not getting paid nor have dedicated time for this, we're doing this on our personal free time.
Second, as @timdeschryver mentioned, this is indeed the desired behavior.
When you use `fireEvent`, the only thing we're doing under the hood is instantiate and dispatch that specific event.
What you're suggesting is that we should also trigger `change` event for the element but that's not how `fireEvent` works as this is just an abstraction of dispatching events.
In order to trigger a `change` event you can go with `fireEvent.change` or better, use [`user-event`](https://github.com/testing-library/user-event) to get an abstraction of the browser events and use `type`.

**Comment by dehghani-mehdi** [comment]
Hello @MatanBobi 
If you have no time or can not support the project or don't know how to do that, simply do not do that, no one force you to do so. You do not owe me and I do not owe you.

Issues meant to be a way to report a bug and improve the software/library, closing it on your personal opinion doesn't help the project at all.

I will file another issue about my request, so someone with deep knowledge about it can answer and explain it. thank you for your time. please do not support any project if you need to get money for it.

**Comment by MatanBobi** [comment]
You're getting this one all wrong. The only reason we're doing this is to help others, we're not looking for money.

To your point, since we're using `dispatchEvent`, and our event is code generated, JS engine probably adds `isTrusted: false`. This means that the input will not be changed.

You can go ahead and try using `createEvent` and setting `{ isTrusted: true }` in the second argument to the `createEvent` function. Not sure that will work, but you can try.

**Comment by dehghani-mehdi** [comment]
I do not understand, if you need more info about the reported issue, why did you close it?

And if you are not sure about what you are talking about, why did you jump into the issue in the first place? please let the expert handle this one, thank you.
