### ISSUE TITLE
Buildqueries types do not allow passing in a 3rd argument for options

### ISSUE THREAD

**Issue by ParamagicDev** [testing-library/dom-testing-library#1145]
- `@testing-library/dom` version: ^8.14.0
- Testing Framework and version:
  
- DOM Environment: Jest 28.1.2, JSDOM 19

### Relevant code or config:

```js
// Label Text
function queryAllByShadowLabelText<T extends HTMLElement = HTMLElement>(container: HTMLElement, id: Matcher, options?: ShadowSelectorMatcherOptions | undefined): T[] {
  const elements = deepQuerySelectorAll(container, ":scope *")

  return elements.map((el) => queryAllByLabelText(el as HTMLElement, id, options)).flat(Infinity) as T[]
}

const getMultipleLabelTextError = (_c: Element | null, id: Matcher) =>
  `Found multiple elements with the label text of: ${id}`
const getMissingLabelTextError = (_c: Element | null, id: Matcher) =>
  `Unable to find an element with the label text of: ${id}`

const [
  queryByShadowLabelText,
  getAllByShadowLabelText,
  getByShadowLabelText,
  findAllByShadowLabelText,
  findByShadowLabelText,
] = buildQueries(queryAllByShadowLabelText, getMultipleLabelTextError, getMissingLabelTextError)

test('byShadowLabelText', async () => {
  const { container } = render(<TextArea />)

  // Types shipped by DOM-testing-library with buildQueries don't have options attached to them.
  // @ts-expect-error
  expect(await findByShadowLabelText(container, /omments/, {exact: false})).toBeInTheDocument()
})
```

### What you did:

I used the `buildQueries` function and the types generated do not match the arguments the functions actually receive. The test above actually passes.

### What happened:

![2022-07-07](https://user-images.githubusercontent.com/26425882/177819810-2afbc5e9-a93d-4738-bf29-a858d8a7c5ab.png)

### Reproduction:

(Will provide once I push up changes on the repo)

### Problem description:

The types are not correct causing TS users to have to use `// @ts-expect-error`

### Suggested solution:

buildQueries should match what the actual functions take in

**Comment by eps1lon** [comment]
The problem is that `buildQueries` tries to infer the parameters from the given functions (`queryAllByShadowLabelText, getMultipleLabelTextError, getMissingLabelTextError`). But in your usage these functions don't have the same parameters so TypeScript infers the smallest type that satisfies all 3 functions: `[id: Matcher]`.

In order to fix it you either have to explicitly pass the parameters or use the same signature for all functions.

Same signature:
```tsx
function queryAllByShadowLabelText<T extends HTMLElement = HTMLElement>(container: HTMLElement, id: Matcher, options?: ShadowSelectorMatcherOptions | undefined): T[] {
  const elements = deepQuerySelectorAll(container, ":scope *")

  return elements.map((el) => queryAllByLabelText(el as HTMLElement, id, options)).flat(Infinity) as T[]
}

const getMultipleLabelTextError = (_c: Element | null, id: Matcher, options?: ShadowSelectorMatcherOptions | undefined) =>
  `Found multiple elements with the label text of: ${id}`
const getMissingLabelTextError = (_c: Element | null, id: Matcher, options?: ShadowSelectorMatcherOptions | undefined) =>
  `Unable to find an element with the label text of: ${id}`
```

[Playground Link](https://www.typescriptlang.org/play?target=99&jsx=4&ssl=27&ssc=96&pln=27&pc=18#code/JYWwDg9gTgLgBAbwLIEMYGMAWBTKAaAIwFdgAbAEwEUjdhsBnPARxqgE8BBU0gITYBkUBbKQAq2AB4w8cKNgB25XAF84AMygQQcAOQABGAxjB5AcwC0pYASgp2Aejkp0MHQCg3S9KTvZ1ReRdgCHk4JWwwalw2AGURbBdoLlIACnQQmBQTXAAuOAAJUSR+AFFSbBAFaTh6eMSoPPoYKBNTAEo8wuKyiqqAbQBdAG4PE0MoNWc-GMwUcggAdzjy+tQMHCgAeTBjEPpENzgjuElnGAB+PIIICHKUeTdlD3t7OEFhUjhxKTc1AKCQnAWNFknwZnNFu8RN8YAAeUQnKQKcj7LqlcqVeTwAC8BSK6N6WIAfGkMll5Lk8d0MVUZMByHk1lhcDIIDtgvJ6Jc4OD5ks6jBoEyNttdpy4AAfOABJRqbLkDpfQYHI7pTnweKYmD7XHhSKsWICpLcUlY8ksuAAIhy9HSYD8ACpLW0PEc5DAiFBQpqqvQAHQgFBgFIpERtODYolAg2ggRCaGSGChz4oVH4npaunkVnsvZtNp+tQ+JMASXkcvkwBgbHDqaVA0eHjVTTgpmwMCQRFIxjA5ShYkTJSgmigEbgKQA+ug8hmqpK4PIu6Qs4y0Mz8HA2WKuXleYtlglBVBhbhRRz9lKZdgK9gFRGiYc4AADABiEBlcBAXZ75RONKx+wLFWmBwDAOBwD4HygYmm5qHkAAkCD0soT5uM28Bth2wD0PQrT9jCQ4jmOk7TnAs5YvOi7cCucAnhuW7ntye78isR50WeezzleN53pGj5PgAqvIQi-oK6gmOQcD3H+hLwEBYGgeBkEiNBUiwQhSHkChTZ7PAfSPsC7BgrMfL4YmeCPphsbMWZUgWUcmHGRCCy2dIj4VuQ1kmZC8YDnZ7kSU5pm+TCFkDGOxBkFQrB0PQKSGZw3BBT5Hyha27adt2wC9tgrmEdAMiYUg2G4WYeXDtALpuKmbCBP4gRitBTQpOGCCPkcfwNRyXyJhwTgtSqxxDe6nqhFRpAjENTyqrpiBwGqmTZKOqi4nIii4Ck8K9U4cD2ESVVDQlyUuSFiamotFIbvYWhavQ9gyAgpwuHkkykLUygug57Zec5rnneaV03b692IE9MAvSgb3YB9lntsdf0LQDMjXSAt0g49EhnBDUMwx1Ek-cFqVnYjS3I0DAHo2D2PvZ9UkLFk8AefDp1SP9pO7eT2qU5jz3qJDNOPEAA)

Explicit parameter type:

```tsx
] = buildQueries<[id: Matcher, options?: ShadowSelectorMatcherOptions | undefined]>(queryAllByShadowLabelText, getMultipleLabelTextError, getMissingLabelTextError)
```

[Playground Link](https://www.typescriptlang.org/play?target=99&jsx=4#code/JYWwDg9gTgLgBAbwLIEMYGMAWBTKAaAIwFdgAbAEwEUjdhsBnPARxqgE8BBU0gITYBkUBbKQAq2AB4w8cKNgB25XAF84AMygQQcAOQABGAxjB5AcwC0pYASgp2Aejkp0MHQCg3S9KTvZ1ReRdgCHk4JWwwalw2AGURbBdoLlIACnQQmBQTXAAuOAAJUSR+AFFSbBAFaTh6eMSoPPoYKBNTAEo8wuKyiqqAbQBdAG4PE0MoNWc-GMwUcggAdzjy+tQMHCgAeTBjEPpENzgjuElnGAB+PIIICHKUeTdlD3t7OEFhUjhxKTc1AKCQnAWNFknwZnNFu8RN8YAAeUQnKQKcj7LqlcqVeTwAC8BSK6N6WIAfGkMll5Lk8d0MVUZMByHk1lhcDIIDtgvJ6Jc4OD5ks6jBoEyNttdpy4AAfOABJRqbLkDpfQYHI7pTnweKYmD7XHhSKsWICpLcUlY8ksuAAIhy9HSYD8ACpLW0PEc5DAiFBQpqqvQAHQgFBgFIpERtODYolAg2ggRCaGSGChz4oVH4npaunkVnsvZtNp+tQ+JMASXkcvkwBgbHDqaVA0eHjVTTgpmwMCQRFIxjA5ShYkTJSgmigEbgKQA+ug8hmqpK4PIu6Qs4y0MyoOHI4c4AADABiEBlcBAXZ75RONKx+wWVcwcBgODgPg+98TcAgajyABIEPTlDu3GbeA2w7YB6HoVp+xhIcRzHSdpzgWcsXnRduBXOBhVwTciW3HcAFV5CEc9BXUExyDge4L0JeAbwfe9H2fERXykd9PzgH8-wAwC9ngPpt2BdgwVmPkoMTPBtxA2NeUheMBykcSjhAoSIQWUT5O3CtyCk4SZI+GEFNIxRlJE2T9LcAYx2IMgqFYOh6FhPp6VXdYLTZMUuTyaT+RWQUoEwrZc3FKUZWwCtsHIAYSQEzhuGM3SE3k1t207btgF7bA1JgGDoBkECkDAiCzEy7KNw8VM2ECfxAjFV8mhScMEG3I4-mqjkvkTDgnHqlVjl691PVCVDSBGXqnlVHjEDgNVMmyUdVFxORFFwFJ4Q6pw4HsIkXSa6Noji1TTMTU0ZopfANq0LV6HsF1eui-bMuO80zvsC7fXsGQEFOFw8kmUhamUG6kpgbSVIe6anpkF6QEu97EC+mAfpQP7sABiT23uw6pEe2bIdeq9Yc+iQzkR5HUeasiQZMvSjvBnHzuht6Pvhkn-sBlAFiyeBNIx6msdp07cYZ-GmaJ771CR1nHiAA)

**Comment by ParamagicDev** [comment]
@eps1lon ahhh this makes sense! thank you! Much appreciated!
