### ISSUE TITLE
wait* utilities take more time since 9.2.0 (running into Timeout)

### ISSUE THREAD

**Issue by kissthom** [testing-library/dom-testing-library#379]
- `react-testing-library` version: 9.2.0
- `react` version: 16.9.5
- `node` version: 12.6.0
- `yarn` version:  1.19.0

### What you did:

Upgraded from version 9.1.4 to 9.2.0. 

### What happened:

Some of our tests which are using the "wait*" utilities provided by the library are running into jest timeout after the upgrade. In some cases waiting for a dom element to appear takes 7-8x times more (~3 seconds) as before with version 9.1.4. 

### Reproduction:

I've created a simple example to reproduce the problem although with this example the difference is not so critical as in our application.  

https://codesandbox.io/s/rtl-wait-slow-g7c21

Steps to reproduce:
1. Run the tests and check out the results in the console (average time for waiting for select.options elements to appear 40-60ms)
2. Switch the rtl version to 9.2.0
3. Run the tests and check out the results again (2-3 times slower) (average time for waiting for select.options elements to appear 110-150ms)

Any help is appreciated.

**Comment by eps1lon** [comment]
Yeah that query can be quite expensive for which I don't really have an easy solution. We can probably optimize it a bit but the general runtime implication of traversing the whole tree will always be there.

So I have some ideas how to make this faster but this is not a priority for me. If somebody wants to work on this then I have a couple of suggestions:
* don't use querySelectorAll but traverse top-down and skip subtrees we know will be inaccessible (aria-hidden, hidden)
* cache `isAccessible` results (I think we have O(n^2) calls it to where n is the number of nodes)

As to your perspective I would generally ask if you really need waitFor queries. Personally I don't find them very useful since I'd like to see explicitly in the test how long something takes in my UI. So far any waiting I used could be replaced with explicitly advancing the timer and then making the assertion. I think this applies to your repro really well. At least I would like my test to fail if it takes 1s instead of .1s to transition. Now this applies mostly to your transitions but not really if you're waiting for some API. Maybe you should rather wait a fixed amount and then expect a certain state. After all your user doesn't want to look for 20s at a spinner either. But I understand that there are some use cases where wait makes more sense. 

Another option may be to reduce to polling time i.e. is it important to assert every frame (16ms) or is every 10 frames (160ms) enough?

And last but not least you can always disabled this check `queryByRole('textobox', { hidden: false })` if you're waiting for something to disappear. If you want to make sure that the queried items are accessible you'll have to wait until the `isAccessible` matcher is done in `jest-dom`.

Either way thank you for taking the time and providing the repro.

**Comment by eps1lon** [comment]
Ok I think I'll prioritize this more since this will be used in an `isAccessible` matcher and I want to expand functionality of `byRole` anyway. I'm not a fan of adding more features before existing ones haven't gotten a polish.

**Comment by kissthom** [comment]
Hi @eps1lon. 
First, thank you for taking a look at it, for the explanation and tips and of course generally for the work on this awesome library.

This issue to solve really does not seem to be simple because I think you will need both mechanism what you suggested (traversing top-down, skipping inaccessible subtrees + caching) to be added to be able to reduce querying time in all cases. 

In my particular case I'm waiting for some state change to happen asynchronously after a fake API call and after that there is also a transition involved (provided by third party lib) which I also have to wait for. 
In the browser itself there is no noticeable performance problem with it, so at the time of writing I'm not worrying about how long the transition takes...but that time will definitely come :). But your argument is totally valid of course.

> Another option may be to reduce to polling time i.e. is it important to assert every frame (16ms) or is every 10 frames (160ms) enough?

I'm not really understand this. How could it be useful to me and how could I apply it? Could you maybe show me some link or example?

> And last but not least you can always disabled this check queryByRole('textobox', { hidden: false })

Indeed, thanks. 
Or I think I can use other queries in my case.
Now that I understand the problem I'm pretty confident that I can use some workaround to solve the issues in our tests. 

> Ok I think I'll prioritize this more since this will be used in an isAccessible matcher and I want to expand functionality of byRole anyway. I'm not a fan of adding more features before existing ones haven't gotten a polish.

👍
If you'd like to I would be happy to help with it.

Should this issue maybe renamed? Because as I pointed out earlier, my original assumption was wrong and it's about the role-queries, not the wait* utilities.

**Comment by kissthom** [comment]
Cool. Thanks for the fix!
