### ISSUE TITLE
[BREAKING]: Deprecate waitForElement

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/dom-testing-library#416]
Just a thought. What if we remove `waitForElement` in favor of `find*` queries?

For history: `waitForElement` was created before `find*` queries. Now that we have `find*` queries, I don't see much of a reason to continue to support it. Most of the time you can use a query, and in the rare situation where you can't use a query to get an element, then you can use `wait`:

```javascript
const element = await wait(() => {
  const el = container.querySelector('.blah')
  if (!el) throw new Error('cannot find element with .blah')
  return el
})
```

It's a bit of boilerplate, but keep in mind that this is not something people should be doing very often nor is it something we want to encourage people to do.

I believe that some of the usages of `waitForElement` could be codemodable, but not all of it.

Thoughts?

**Comment by timdeschryver** [comment]
Could the same thing be said about `waitForElementToBeRemoved`? 
Asking because the API design with `waitForElement` and `waitForElementToBeRemoved` compliments each other nicely imho, but both functions can be written with `wait`. That's why I would expect to see both functions, or none of the two.

**Comment by kentcdodds** [comment]
Fair point... Hmmm... I'm leaning toward keeping it as-is then.
