### ISSUE TITLE
snapshot in a waitFor doesn't seem to work right in 7.x

### ISSUE THREAD

**Issue by benmonro** [testing-library/dom-testing-library#484]
- `dom-testing-library` version: 10.x
- `node` version: 12.14
- `npm` (or `yarn`) version: 6.13

Relevant code or config

when using `waitFor` with `expect().toMatchSnapshot()` I've seen some strange behaviors. 

What you did:
```js
test("should match snapshot async", async () => {
  const mockApi = jest.fn();
  render(<App callApi={mockApi} />);
  fireEvent.click(screen.getByText("click me"));

  await waitFor(() => {
    // expect(mockApi).toBeCalled(); //fails without this.  but why?
    expect(mockApi.mock.calls).toMatchSnapshot()
  })

})


test("should show stuff", async () => {
  render(<App />);
  waitFor(() => {

    expect(document.body).toMatchSnapshot();
  });
});

```
What happened:
![image](https://user-images.githubusercontent.com/399236/76646716-b8118d80-6518-11ea-8fae-a2fdcc03d8cc.png)
![image](https://user-images.githubusercontent.com/399236/76649268-8a7b1300-651d-11ea-93c5-bccc0ced0e7e.png)

Reproduction repository:
https://github.com/testing-library/dom-testing-library-template
https://github.com/benmonro/rtl-wait-for-issue

Problem description:
expect.toMatchSnapshot doesn't seem to work properly in a waitFor.  You'll notice i have 2 different usages.  one in which the dom doesn't change, it just calls an api and matches on the mock for that api.  another where it waits for a snapshot of the dom to match.  My examples are a bit contrived, but they do highlight the problem we're seeing. I would of course use getByText to look for 'stuff' but it still makes me wonder why this usage of `waitFor` isn't working w/ toMatchSnapshot the way I would think it would
Suggested solution:

**Comment by kentcdodds** [comment]
I think that this is still not recommended because the point of `waitFor` is so you can wait a non-deterministic amount of time for something to happen and that means that your callback will be called a non-deterministic number of times which will cause problems with snapshots. Every call to that assertion will result in a snapshot update which is not going to be what you want anyway.

So yeah, don't use snapshots in the async utils.

We should document this. I don't think we can do anything to change it...

**Comment by alexkrolick** [comment]
```js
  await waitFor(() => {
    // expect(mockApi).toBeCalled(); // fails without this.  but why? 🚩🚩🚩
    expect(mockApi.mock.calls).toMatchSnapshot()
  })
```

FWIW, it looks like that line failing shortcircuits the wait, so it only moves onto the snapshot call one time. Which agrees with what Kent it saying, which is that calling it more than once will error. I think it's because of how the snapshot reporter works in Jest (ie, how it says "N snapshots updated" in the test report, and has the interactive prompt to update in watch mode). It might work in some other implementation like a Mocha plugin.

**Comment by kentcdodds** [comment]
Going to go ahead and close this. If someone wants to do more with docs feel free.
