### ISSUE TITLE
`screen.querySelector`

### ISSUE THREAD

**Issue by timdeschryver** [testing-library/dom-testing-library#512]
### Describe the feature you'd like:

We're promoting the usage of `screen` to use queries.
At rare occasions, these queries are not sufficient enough and we can fallback to `querySelector` and `querySelectorAll`.

I'm proposing that we also add these "queries" on `screen`.
Adding these "queries" improves the consistency of using `screen`, but could this new feature encourage bad practices if we expose the `querySelector` method? 

### Describe alternatives you've considered:

As an alternative we can get the container of the rendered component, or use `document` directly in order to use the `querySelector` method.

**Comment by kentcdodds** [comment]
Hi @timdeschryver,

I understand what you're trying to accomplish here, but I'm strongly against it. Everything we add to the API makes it "blessed" and in some ways "encouraged." Sometimes we do this for some things that aren't really recommended because they're better than the alternative (for example, test IDs rather than class names). I'm also willing to do this when the workaround for a common problem is too difficult.

However, `querySelector` and `querySelectorAll` falls into neither of these categories. As you mentioned, if people really do want to use those, then they can use `document.querySelector`. In fact, if we implemented this feature on screen it would literally be:

```js
screen.querySelector = (...args) => document.querySelector(...args)
```

The benefit is very small and the cost is high because then we turn an API we don't want people to use normally into one that's blessed.

I'm still open to hearing other people's opinions, but I'm pretty confident that this is not something we'll do, so I'll close this issue for now.

Thanks for all you do Tim!

**Comment by timdeschryver** [comment]
Thanks @kentcdodds !
I agree with what you're saying and thank you for sharing your thoughts.

**Comment by alexkrolick** [comment]
Right, "screen" is intentionally generic in that almost all the queries from `@testing-library/react-native` (for mobile) and `@testing-library/dom` are the same and query (roughly) the accessibility object tree; web APIs like querySelector break out of that.
