### ISSUE TITLE
Role `mark` is not found

### ISSUE THREAD

**Issue by bengry** [testing-library/dom-testing-library#669]
- `@testing-library/dom` version: 5.10.1
- Testing Framework and version: Jest (whatever comes with `react-scripts@3.1.2`
- DOM Environment: jsdom

### Relevant code or config:

```js
// App.js
export default () => (
  <p>
    Several species of <mark>salamander</mark> inhabit the temperate rainforest
    of the Pacific Northwest.
  </p>
);

// App.spec.js
test("React Testing Library works!", () => {
  render(<App />);
  expect(screen.getByRole("mark")).toHaveTextContent("salamander");
});
```

### What you did:
The [`mark`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark) tag does not have an implicit aria role according to MDN. However, if you look in Chrome's DevTools (Chrome 83) it does have a Role of `mark`:
![image](https://user-images.githubusercontent.com/260431/85556849-ea5e7b00-b62f-11ea-8e69-076856aec5cc.png)

Additionally, it's recommended to use `mark` vs. a regular `span` when marking text with relevance to the user.

### What happened:

DOM testing library didn't find the `<mark>` tag.

### Reproduction:

https://codesandbox.io/s/react-testing-library-role-mark-9yydb

### Suggested solution:

I'm not sure if it's entirely correct, since `<mark>` does not have an implicit aria role, as mentioned above, but a possible solution would be to find it by role of `mark`?

The current workaround I'm using is to use the `selector` option and pass in `mark`.

**Comment by eps1lon** [comment]
[`<mark>` currently not mapped by `html-aam`](https://w3c.github.io/html-aam/#el-mark). There's also currently not role named `mark`

May be spec lagging behind or implementors making judgment calls. 

Chrome's and Firefox's accessibility inspector use more roles than just the ones from wai-aria. We can't really start considering them since they sometimes have different names depending on the browser.

`ByRole` is intended to query like a screen reader would and there are currently some a11y concerns listed for the `mark` element. Overall it doesn't sound like something useful to query in `ByRole`.

It sounds like you want to test that a given text is spoken a certain way and from what I've read you shouldn't force this too much and let the user control it. In the end you're probably better of with manual testing with assistive technology.

**Comment by bengry** [comment]
@eps1lon I want to test that a certain text is the one that's being highlighted (i.e. `<mark>`-ed).
Sounds like my workaround is the best way to do it until there's an `html-aam` mapping for `<mark>` then:
> The current workaround I'm using is to use the selector option and pass in mark.

Is there any other, better way to achieve what I want?

**Comment by eps1lon** [comment]
> Is there any other, better way to achieve what I want?

Or [build a custom query](https://testing-library.com/docs/dom-testing-library/api-helpers#custom-queries). 

Until ARIA introduces a `mark` role we shouldn't change anything. Unless we switch from ARIA to concrete accessibility APIs but that's out of scope for this issue.

Closing since there's no actionable item for us here.
