### ISSUE TITLE
Asserting elements are not present after timeout

### ISSUE THREAD

**Issue by galkn** [testing-library/dom-testing-library#699]
The docs indicate using `queryBy` to assert that an element is not present, but I'd like to use an equivalent of `findBy` that doesn't throw an exception for the purpose of asserting that an element is not present after a timeout has passed. Is there a way to do this without using `waitFor`? 

Thanks.

**Comment by kentcdodds** [comment]
Is there any reason [`waitForElementToBeRemoved`](https://testing-library.com/docs/dom-testing-library/api-async#waitforelementtoberemoved) won't work?

**Comment by galkn** [comment]
I'm not sure if it would work in my use case, since the element was never (and won't be) in the DOM. I believe `waitForElementToBeRemoved` would immediately resolve if the element is not found.

**Comment by galkn** [comment]
More specifically, I want to assert that after some action is taken that triggers an async call, a modal does not show up.

**Comment by kentcdodds** [comment]
I see, this makes sense, but I don't think it's common enough (or recommended enough) to warrant inclusion in the library. Particularly because it's not really deterministic. How long should you really wait for?

Here's how you could do this though:

```javascript
import {act} from '@testing-library/react'

const sleep = t => new Promise(resolve => setTimeout(resolve, t))

// ... in your test
await act(() => sleep(200))
// assert it's not there
```

Because we won't be including anything like this in the library, I'll go ahead and close this. Thanks!

**Comment by kentcdodds** [comment]
You should probably use fake timers for that test so it doesn't take so long
