### ISSUE TITLE
getByLabelText not working with id on 7.21.2+

### ISSUE THREAD

**Issue by amandapouget** [testing-library/dom-testing-library#714]
- `@testing-library/dom` version: 7.21.2, 7.21.3, 7.21.4
- Testing Framework and version: Jest 26.1.0
  
- DOM Environment:
  
testing-library/jest-dom 5.11.1
react-dom 16.13.1

### Relevant code or config:

```html
// Created using react-select
<div id="foo-123"> ... </div>
<label for="foo-123">Foobar</label>
```
```js
const dropdown = form.getByLabelText('Foobar')
expect(dropdown).toHaveContent('Placeholder...')
```

### What you did:

Previously, this test passed just fine (on testing-library/dom 7.21.1 and below).

### What happened:

TestingLibraryElementError: Found a label with the test of: Foobar, however no form control was found associated to that label. Make sure you're using the "for" attribute or "aria-labelledby" attribute correctly.

### Reproduction:

(If it's not obvious how this was broken on the recent change, let me know and I'll make a repo.)

### Problem description:

Cannot test labels linked to divs by id.

### Suggested solution:

Something about the changes in 7.21.2 broke this.

**Comment by delca85** [comment]
Hi! Thanks for reporting this issue.

I think the problem should be in [this](https://github.com/testing-library/dom-testing-library/blob/f854cde7cef103c939c40f3b56c11543604ce627/src/queries/label-text.js#L91) line because we are not querying for `div`elements.

I could work on it later today if it sounds good for all of you.

**Comment by kentcdodds** [comment]
Hold on, I'd like to check on something first.

**Comment by amandapouget** [comment]
Thank you guys!!!

**Comment by kentcdodds** [comment]
Ah, yep, this is what I suspected. According to [the spec](https://html.spec.whatwg.org/multipage/forms.html#category-label):

> Some elements, not all of them  [form-associated](https://html.spec.whatwg.org/multipage/forms.html#form-associated-element), are categorized as  labelable elements. These are elements that can be associated with a  `[label](https://html.spec.whatwg.org/multipage/forms.html#the-label-element)`  element.
> 
> -   `[button](https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element)`
> -   `[input](https://html.spec.whatwg.org/multipage/input.html#the-input-element)`  (if the  `[type](https://html.spec.whatwg.org/multipage/input.html#attr-input-type)`  attribute is  _not_  in the  [Hidden](https://html.spec.whatwg.org/multipage/input.html#hidden-state-(type=hidden))  state)
> -   `[meter](https://html.spec.whatwg.org/multipage/form-elements.html#the-meter-element)`
> -   `[output](https://html.spec.whatwg.org/multipage/form-elements.html#the-output-element)`
> -   `[progress](https://html.spec.whatwg.org/multipage/form-elements.html#the-progress-element)`
> -   `[select](https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element)`
> -   `[textarea](https://html.spec.whatwg.org/multipage/form-elements.html#the-textarea-element)`
> -   [form-associated custom elements](https://html.spec.whatwg.org/multipage/custom-elements.html#form-associated-custom-element)

So unfortunately the test that was passing was passing due to a bug in our implementation and @delca85's changes fixed that bug.

You can observe the browser's behavior by copy/pasting the HTML into a jsbin and looking at the accessibility panel:

![image](https://user-images.githubusercontent.com/1500684/88415421-b5168b80-cd9b-11ea-936e-2f00a2e04133.png)

Notice that there's no label for this element.

If you really *need* to label a div, you can use `aria-label` or `aria-labelledby` and that should work for the query as well:

![image](https://user-images.githubusercontent.com/1500684/88415505-d7100e00-cd9b-11ea-8d38-7983de96dcfb.png)

You'll notice that *does* have a label now, and if you try that in [the testing playground](https://testing-playground.com/?markup=DwEwlgbgBGILwCIBmB7FBaAjAJgMwKgEMAnMQ9AG0ICMBTCi2kagT0VQyrooQD4oAdEKjAA9OAi8AUMC70Y8ZGko16BVMXbKc%2BXgDE01EmLkVeQA&query=M4YwTgphB2B0DmEAuAhAngGQIYCMIBsAVCADyQAoB6AMwHtacsxKBLASiA), that works :)

Good luck!

**Comment by amandapouget** [comment]
I am using react-select, so that is where the label and div are coming from.

Looks like it's a problem for them, making this version of dom-testing-library not compatible with the latest react-select (and selectEvent).

Will report over there.

**Comment by ebonow** [comment]
Greetings @amandapouget,

Sorry that there has not yet been a reply to you in react-select, but happy to provide some input even if post-mortem.

When you say above in the code
```js
// Created using react-select
<div id="foo-123"> ... </div>
<label for="foo-123">Foobar</label>
```
It should be noted that react-select does not create any labels which is perhaps why there may have been some confusion so I can only assume that the first div is what is "created by react-select" and the second element is additional JSX rendered to provide a label for the react-select.

If this is the case, perhaps try using the prop `inputId` instead of `id`. This is the prop that should be used to define the id for the input and linked to the label for it.

**Comment by ebonow** [comment]
Additionally, it may be worth noting that the label component could potentially be wrapped around the react-select as well without the need for id's.

``` html
<label>
  <span>Foobar</span>
  <!-- React-Select goes here -->
</label>
```
