### ISSUE TITLE
getByLabelText broke between 7.14.2 and latest

### ISSUE THREAD

**Issue by Floriferous** [testing-library/dom-testing-library#731]
A test using `getByLabelText` that was succeeding (as of 7.14.2) for a while started failing suddenly with `Unable to find a label with the text of: Select` when I upgraded to 7.20.x.

Here's the code in question:

```js
expect(!!getByLabelText('Select')).to.equal(true);
```

I saw a lot of commits made to `byLabelText` in the last few releases, so I'm wondering if this was a mistaken breaking change, or if this code should've never worked?

Here's the pretty printed HTML of the react component:

```html
<div
      class="MuiFormControl-root MuiTextField-root MuiFormControl-marginNormal MuiFormControl-fullWidth"
    >
      <label
        class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-marginDense MuiInputLabel-outlined MuiFormLabel-filled Mui-required Mui-required"
        data-shrink="true"
        for="uniforms-0000-0000"
        id="uniforms-0000-0000-label"
      >
        Select
        <span
          aria-hidden="true"
          class="MuiFormLabel-asterisk MuiInputLabel-asterisk"
        >
           
          *
        </span>
      </label>
      <div
        appearance="checkbox"
        class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-fullWidth MuiInputBase-formControl MuiInputBase-marginDense MuiOutlinedInput-marginDense"
        intl="[object Object]"
        recommendedvalues="yo,hola"
      >
        <div
          aria-haspopup="listbox"
          aria-labelledby="uniforms-0000-0000-label uniforms-0000-0000"
          class="MuiSelect-root MuiSelect-select MuiSelect-selectMenu MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMarginDense MuiOutlinedInput-inputMarginDense"
          id="uniforms-0000-0000"
          role="button"
          tabindex="0"
        >
          other
        </div>
        <input
          aria-hidden="true"
          class="MuiSelect-nativeInput"
          name="text"
          required=""
          tabindex="-1"
          value="other"
        />
        <svg
          aria-hidden="true"
          class="MuiSvgIcon-root MuiSelect-icon MuiSelect-iconOutlined"
          focusable="false"
          viewBox="0 0 24 24"
        >
          <path
            d="M7 10l5 5 5-5z"
          />
        </svg>
        <fieldset
          aria-hidden="true"
          class="PrivateNotchedOutline-root-1 MuiOutlinedInput-notchedOutline"
        >
          <legend
            class="PrivateNotchedOutline-legendLabelled-3 PrivateNotchedOutline-legendNotched-4"
          >
            <span>
              Select
               *
            </span>
          </legend>
        </fieldset>
      </div>
    </div>
```

Anyways, I pinned back to 7.14.2 for now.

**Comment by kentcdodds** [comment]
Hi @Floriferous,

The aria-labelledby in there is kind of odd because it looks like it's labeling itself? Also, the label already has a `for` attribute, but labels can't have a `for` that points to a non-labelable element (like a `div`).

I'm pretty sure you should be ok with `aria-labelledby="uniforms-0000-0000-label"` and remove the `for` on the label.

Either way, you're probably better off with a `ByRole` query. Check this out: https://testing-playground.com/gist/f0980e18cef09084d5fe243a4c4a1f30/8a416370b38cc024aa6fd75b9e3a835e2143c927

Hope that helps. Good luck!

**Comment by eps1lon** [comment]
> The aria-labelledby in there is kind of odd because it looks like it's labeling itself?

That is valid if you want to construct a label of multiple elements. By doing that you ensure that the element itself is part of the label as well as the other elements you wish to include.

While the `for` is redundant it is harmless to assistive technology. Though I don't know where it's coming from since it isn't part of the default markup created by materail-ui:
![Screenshot from 2020-08-06 21-05-44](https://user-images.githubusercontent.com/12292047/89571874-a9f63d80-d828-11ea-9ee1-58e55a1e07ab.png)

**Comment by Floriferous** [comment]
It's probably coming from https://github.com/vazco/uniforms, the library we're using for our forms. I'll check if it's something we're introducing.
