### ISSUE TITLE
await waitFor( ... ) behavior doesn't match the documentation

### ISSUE THREAD

**Issue by bvanyushin** [testing-library/dom-testing-library#765]
- `@testing-library/dom` version: 7.24.1
- Testing Framework and version: jest: 25.2.4
- DOM Environment: jsdom 15.2.1
  

### Relevant code or config:

```js
describe('test', () => {
  it('acts like in documentation', async () => {
    let counter = 0;
    setTimeout(() => counter = 1, 1);
    setTimeout(() => counter = 3, 1000);

    await waitFor(() => { expect(counter).toEqual(3) })
    expect(counter > 1).toEqual(true)
  })
})
```

### What you did:

I am trying to use waitFor to wait until variable will get proper value. In sample code I expect, that check `expect(counter > 1).toEqual(true)` will be launched only after check in `waitFor` passes (as written in documentation) 

```js
// ...
// Wait until the callback does not throw an error. In this case, that means
// it'll wait until the mock function has been called once.
await waitFor(() => expect(mockAPI).toHaveBeenCalledTimes(1))
// ...
```

### What happened:

actually checks failed 
```
    expect(received).toEqual(expected) // deep equality

    Expected: 3
    Received: 1

    <html>
      <head />
      <body />
    </html>

   9 |     setTimeout(() => counter = 3, 1000);
  10 |
> 11 |     await waitFor(() => { expect(counter).toEqual(3) })
     |                                           ^
  12 |     expect(counter > 1).toEqual(true)
  13 |   })
  14 | })

      at app/fake.spec.tsx:11:43
      at runWithExpensiveErrorDiagnosticsDisabled (node_modules/@testing-library/dom/dist/config.js:51:12)
      at checkCallback (node_modules/@testing-library/dom/dist/wait-for.js:102:75)
      at Timeout.callback (node_modules/jsdom/lib/jsdom/browser/Window.js:643:19)
```

### Reproduction:

https://github.com/bvanyushin/wait-for

### Problem description:

Behavior doesn't match the documentation, and makes difficult to test components with cascade api calls.

**Comment by kentcdodds** [comment]
Hi @bvanyushin,

The problem is that the default timeout is 1000ms, if you change your test to account for this then it passes as documented:

```javascript
describe('test', () => {
  it('acts like in documentation', async () => {
    let counter = 0;
    setTimeout(() => counter = 1, 1);
    setTimeout(() => counter = 3, 500);

    await waitFor(() => { expect(counter).toEqual(3) })
    expect(counter > 1).toEqual(true)
  })
})
```

(Keep in mind that timings in JavaScript engines isn't always precise, so even though the timeout is set to 1000ms and you set a timeout for the same amount of time, that doesn't mean things will always work that way). If you can't control how fast your tests run, then you can adjust the timeout time: https://testing-library.com/docs/dom-testing-library/api-async#waitfor

```javascript
describe('test', () => {
  it('acts like in documentation', async () => {
    let counter = 0;
    setTimeout(() => counter = 1, 1);
    setTimeout(() => counter = 3, 1000);

    await waitFor(() => { expect(counter).toEqual(3) }, {timeout: 5000})
    expect(counter > 1).toEqual(true)
  })
})
```

If you'd like to configure this globally then you can using the `asyncUtilTimeout` config: https://testing-library.com/docs/dom-testing-library/api-configuration

I hope that helps! Good luck.
