### ISSUE TITLE
jest.useRealTimers() is not a function when running RTL tests in jest-electron environment

### ISSUE THREAD

**Issue by Manish3323** [testing-library/dom-testing-library#905]
I decided to try using `jest-electron` environment in our jest test setup because `jsdom` environment has some missing browser functionality that we were using.

-    "@testing-library/jest-dom": "^5.11.9",
-   "@testing-library/react": "^11.2.3",
-    "@testing-library/user-event": "^12.6.3",
- `node` version: v15.10
- `npm` version: v7

### Relevant code or config:
pasting only necessary changes here of my `jest.config.js` 
```js
{
 .
 .
  runner: 'jest-electron/runner',
  testEnvironment: 'jest-electron/environment',
  .
  .
  .
}
```

### What you did:

ran `npm run test`

### What happened:

i think helpers file inside RTL /dom is calling jest.useFakeTimers()..
which is not available in jest-electron environment.

The error that i'm getting is shown in the following SS.
<img width="1137" alt="Screenshot 2021-02-27 at 1 16 00 PM" src="https://user-images.githubusercontent.com/16453816/109381051-f2c52f00-78fd-11eb-80e4-e206fcf55834.png">

### Reproduction:
Small repro can be created on local machine on following these steps.
clone : https://github.com/tmtsoftware/esw-ocs-eng-ui
`git checkout jest-branch`
`npm i & npm t`

### Problem description:

RTL/jest-dom helpers are calling jest.timers functionality without checking jest-environment.

### Suggested solution:

there could be some kind of check related to which environment jest is currently running before this line.
` @Testing-Library/dom/dist/helpers.js:38 `.

**Comment by SimenB** [comment]
Seems to be an issue with the env: https://github.com/hustcc/jest-electron/blob/b5887476eb639549c9317dd26b839d961ac58573/src/environment.ts#L38-L43

**Comment by EsoterikStare** [comment]
I'm running into a similar issue when trying to upgrade the @material-ui dependency from `@testing-library/dom@7.22.1` to `@testing-library/dom@7.28.1` and above. After that upgrade, I get the exact same error mentioned here. 

The issue is that [when `helpers.js` checks if `typeof jest !== 'undefined'`](https://github.com/testing-library/dom-testing-library/blob/master/src/helpers.js#L9), it's actually true because `jest` is `null` at this point for some reason, which has a type of `object` (thanks js), so it makes it past that check. 

Later, when it [tries to call `jest.useRealTimers();`](https://github.com/testing-library/dom-testing-library/blob/master/src/helpers.js#L27) it errors, because `jest` is `null` and has no such property to invoke. 

This is not the case before the upgrade and it is the case after the upgrade, and I've checked to make sure there are no other changes to the dependencies so it seems like it's a direct result of changes between those versions.

Some other relevant info for this scenario:
- MUI uses mocha, not jest, so the jest binary isn't even defined anywhere in the repo context. (I've also ensured it's not installed globally and isn't defined in the test execution context at all.)
- Because jest is not in play at all, there is no `testEnvironment` set. NODE_ENV is being used to drive some functionality, but seems completely unrelated.

It may be unrelated, but it seems very similar and I'm really scratching my head to understand this issue.

@Manish3323, could you inspect the type and value of `jest` right before that check in the helpers.js file by tossing a console in node_modules code? Just curious what the value might be. That check is clearly not catching all bad cases.

**Comment by eps1lon** [comment]
@EsoterikStare What we're doing in Material-UI is quite esoteric (gotta make that pun) and not really relevant here. Let's discuss this in the mui-org repo.

What Material-UI is doing: React only triggers unexected act warnings when `typeof jest !== 'undefined'` so we're just setting it to `null` to get them. We don't have any problems with dom-testing-library since we don't rely on `waitFor` and the general advise is to not use `waitFor` in our component tests. Component-library tests have different requirements than component-app tests.

**Comment by EsoterikStare** [comment]
@eps1lon Got it! Thanks!

**Comment by ZheyangSong** [comment]
In case this helps anyone facing the same issue, this breakage seemly is introduced by a patch version of 7.29. You can try to downgrade this library to a 7.28.x or lower. You should get this issue gone.

Hope this will get the testing-library project team's attention as well. For me, the module I use, its custom environment doesn't define `userRealTimers`. https://github.com/facebook-atom/jest-electron-runner/blob/master/packages/electron/src/Environment.js#L16

**Comment by eps1lon** [comment]
@Manish3323 Thanks for the repro. This helped a lot verify the fix.

**Comment by Manish3323** [comment]
@eps1lon.. thanks for looking into this 🙌 ..
i have updated all my package's to their latest versions..(basically ran `npm-check-updates -u`)
the error mentioned above persists..
what am i missing ?

**Comment by eps1lon** [comment]
@Manish3323 Could you add a repro for investigation? You're probably still pulling in an older version.

**Comment by NicholasOliveira** [comment]
Eu continuei com o mesmo problema utilizando o seguinte ambiente.

"@jest-runner/electron": "^3.0.1",
    "@testing-library/jest-dom": "^5.12.0",
    "@testing-library/react": "^11.2.6",
    "@testing-library/react-hooks": "^5.1.2",
    "@testing-library/user-event": "10.3.4",

a solução foi incluir na linha 26 do arquivo:
@testing-library/dom/dist/helpers.js 

```
function hasJestTimers() {
  
  **if(jest.useRealTimers !== 'function') return;** // add this line
  
  return typeof jest !== 'undefined' && jest !== null && typeof jest.useRealTimers === 'function';
}
```

**Comment by Ruluk** [comment]
For the record, the same thing is happening to me when using the latest RTL in CodeSandbox.

Test code:
```javascript
import React from 'react';

import { render } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';

import App from './App';

describe('App', () => {
  test('it should render', () => {
    render(<App />);
  });
});
```

Dependencies:
```json
{
    "@testing-library/react": "11.2.6",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "4.0.0"
}

**Comment by Auroratide** [comment]
I also received this problem, but while using Svelte Testing Library instead. The funky thing is `typeof jest.useRealTimers` is indeed "function", and yet it is unable to be called as one; therefore, it's passing the check implemented in the PR yet continuing to fail in execution.

Electron runner does not define `useRealTimers`, so it isn't clear to me at what point it becomes a function-but-not-a-function. For now I am able to pin this library to 7.28.1, where it works without issue.

I don't have a minimal repro, but here's [my repo](https://github.com/Auroratide/nonupo.io) where I was exhibiting the issue before pinning @testing-library/dom.
